version: '3.2'
services:
    frontend:
        image: aergoscan/front:2.4.0
        build:
            context: .
            args:
                AERGO_NODE: http://local-api-http.aergo.io
                API_URL: http://api2-local.aergoscan.io/v3
    backend:
        image: aergoscan/api:2.4.0
        build:
            context: ./aergoscan_v2_api
