version: '3.2'
services:
    frontend:
        image: aergoscan/front:2.4.0
        build:
            context: .
            args:
                ARG_AERGO_NODE_HOST: http://local-api-http.aergo.io
                ARG_API_URL: http://api2-local.aergoscan.io/v3
    backend:
        image: aergoscan/api:2.4.0
        build:
            context: ./aergoscan_v2_api
            args:
                ARG_HOST_API: http://aergoscan-api
                ARG_SELECTED_NETWORK: local
                ARG_ES_URL: aergoscan-es:9200
                ARG_HTTP_PORT: 3000
